

DROP TABLE IF EXISTS accounts CASCADE;
CREATE TABLE accounts (
  email CHARACTER VARYING PRIMARY KEY,
  phone CHARACTER VARYING,
  salt CHARACTER VARYING,
  hashed_password CHARACTER VARYING
);

DROP TABLE IF EXISTS domains CASCADE;
CREATE TABLE domains (
  name CHARACTER VARYING PRIMARY KEY,
  owner CHARACTER VARYING NOT NULL REFERENCES accounts
);

DROP TABLE IF EXISTS dns_records;
CREATE TABLE dns_records (
  name CHARACTER VARYING NOT NULL,
  type CHARACTER VARYING NOT NULL,
  class CHARACTER VARYING NOT NULL,
  ttl INTEGER NOT NULL DEFAULT 300
);

DROP TABLE IF EXISTS certificates;
CREATE TABLE certificates (
  sha256 CHARACTER VARYING PRIMARY KEY,
  domain CHARACTER VARYING REFERENCES domains,
  public_key CHARACTER VARYING NOT NULL,
  revoked BOOLEAN DEFAULT false
);

